version: '3.2'

networks:
  default:
    external: true
    name: ${DECK_DCL_NETWORK}

services:
  test-e2e:
    image: ${DECK_DIMAGE_MAIN__IMAGE}
    command: "bash -c 'cat /_confs/rclone.conf && rclone mkdir lms3:do-ob && rclone lsd lms3: | grep do-ob'"
    environment:
      - RCLONE_CONFIG=/_confs/rclone.conf
    volumes: 
      - "/home/yairda/_wd/ydtools/agr-ydtools/decks/ydtools.st223.test-plex/rclone.conf.local-brigde.toml:/_confs/rclone.conf"
