# https://taskfile.dev

version: '3'


vars:
  _name_: deps tasks
  
  _required: |-
    _taskfilename_: including filename
  
  _kv_cmdt_query: |-
    '.confs as $names 
    | .items[] 
    | {
        "key":.key, 
        "value":.value,  
        "bashcmd":"items="+.value + " " + $names[.key].default,
        "dockcmd":"RUN apt-get update && " + "items="+.value + " " + $names[.key].default,
        "cmdt":$names[.key].default }
    ' -j
  _dock_cmd_render_: |-
    | yq0 e '[.]' - -P | yq0 e '.[0].dockcmd' -

tasks:
  # dockcmd: |-
  #   RUN apt-get update && \
  #       items={{.value}} \
  #       apt-get install -y ${items}

  list:
    desc: list deps items
    cmds:
      - yq4 e '.items' {{._taskfilename_}}
  
  gen-blocks:
    desc: generates blocks
    cmds:
      - yq0 eval {{._kv_cmdt_query}} {{._taskfilename_}} {{._dock_cmd_render_}}
    silent: true
  
  inline-blocks:
    desc: generates blocks
    cmds:
      - yq0 eval {{._kv_cmdt_query}} {{._taskfilename_}} {{._dock_cmd_render_}}
    silent: true

# deps:gen-blocks | yq0 e '[.]' - -P | yq0 e '.[0].dockcmd' -