# https://taskfile.dev

version: '3'


vars:
  _name_: deps tasks
  
  _required: |-
    _taskfilename_: including filename
  
  _kv_cmdt_query: |-
    '.confs as $names 
    | .items[] 
    | {
        "key":.key, 
        "value":.value,  
        "bashcmd":"items="+.value + " " + $names[.key].default,
        "dockcmd":"RUN apt-get update && "  + $names[.key].default + ".value + " ",
        "cmdt":$names[.key].default }
    ' -j
  _dock_cmd_render_: |-
    | yq0 e '[.]' - -P | yq0 e '.[0].dockcmd' -

tasks:
  # dockcmd: |-
  #   RUN apt-get update && \
  #       items={{.value}} \
  #       apt-get install -y ${items}

  list:
    desc: list deps items
    cmds:
      - yq4 e '.items' {{._taskfilename_}}
  
  gen-blocks:
    desc: generates blocks
    cmds:
      - echo '{''{' 'shell "task deps:gen-blocks"' '}''}'
      - yq0 eval {{._kv_cmdt_query}} {{._taskfilename_}} {{._dock_cmd_render_}}
      - echo '# .@@set=block.over'
    silent: true
  
  inline-dock-blocks:
    desc: generates blocks
    cmds:
      - mkdir -p _out_
      - |-
        cat Dockerfile \
        | gucci \
        | sed -z -e 's/\.@@set=block\.over.*\.@@set=block\.over/\.@@set=block\.over/g' \
        | tee _out_/Dockerfile
      - mv _out_/Dockerfile Dockerfile

    silent: true
  
  inline-dock-blocks.py:
    desc: generates blocks
    cmds:
      - cmd: |
          python -c '
          from pathlib import Path
          text_orig = Path("Dockerfile").read_text()
          text_orig.split("# .@@set=block.content.exp=deps:inline-dock-blocks")[1].split("# .@@set=block.over")
          '
    silent: true
# deps:gen-blocks | yq0 e '[.]' - -P | yq0 e '.[0].dockcmd' -