version: '3'
dotenv: ['.env']
vars:
  _taskfilename_: Taskfile.yml
includes:
  deck: ../../tasks/deck.tasks.yml
  deps: tasks.deps.tasks.yml
  stacks: tasks.stacks.tasks.yml

tasks:
  gen-blocks:
    - task: deps:gen-blocks
  
  build:
    - task: deps:inline-dock-blocks
    - task: deck:docker:build
  test: |-
    bash -c '
    PYTHONPATH=.
    MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password _out_/minio server _out_/data &
    sleep 3
    pytest tests src -s
    kill %-
    '

---
kind: deps.docker.conf-v4.yml
items:

  - key: os:install
    value: |-
      bash \
      curl \
      wget \
      unzip \
      git

  - key: pip:install
    value: |-
      pytest \
      spur \

confs:

  os:install: 
    default: |-
      apt-get install -y {{.value}}

  pip:install: 
    default: |-
      pip install {{.value}}