FROM ubuntu:18.04

###
# RUN apt update -y \
#     && apt install -y \
#        ${items}
###

# .@@set=block.init block.manager=deps.docker.conf-v4.yml
# .@@set=block.content={{shell "task -t deps.docker.conf-v4.yml deps:gen-blocks"}}
# .@@set=block.over

RUN uname -r
