FROM ubuntu:18.04

###
# RUN apt update -y \
#     && apt install -y \
#        ${items}
###
# .@@set=block.init block.content= block.managed=deps.docker.conf-v4.yml
# .@@set=block.over block.managed=deps.docker.conf-v4.yml 

RUN uname -r
