version: '3'
dotenv: ['.env']
vars:
  _taskfilename_: Taskfile.yml
includes:
  deck: ../../tasks/deck.tasks.yml
  deps: ../../tasks/deps.tasks.yml

tasks:
  gen-blocks:
    - task: deps:gen-blocks
      vars:
        items: yq e '.items' {{._taskfilename_}}
  
  inline-dock-blocks:
    desc: generates blocks
    cmds:
      - mkdir -p _out_
      - |-
        cat Dockerfile \
        | gucci \
        | sed -z -e 's/\.@@set=block\.over.*\.@@set=block\.over/\.@@set=block\.over/g' \
        | tee _out_/Dockerfile
      - mv _out_/Dockerfile Dockerfile

---

items:

  - key: os:install
    value: |-
      ' \
      curl \
      wget \
      git \
      yq \
      '

confs:
  os:install: 
    default: |-
      apt-get install -y ${items}
  