# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  ensure:network:
    desc: _
    cmds:
      - docker network create -d bridge ${DECK_DCL_NETWORK}

